spring.application.name=Final_Project

## mongo db setup
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

logging.level.org.springframework.data.mongodb.core=DEBUG

jwt.secret=cpsc449-devtasks-secret0key-must-be-at-least-256-bits-long!
jwt.expiration=84000000